version: '3'

services:
    storage_database:
        container_name: storage_database
        build: 
            context: ./
            dockerfile: ./database/Dockerfile
        image: "ntw_storage:latest"
        restart: unless-stopped
        tty: true
        env_file:   
            - ./conf/common.env
            - ./conf/database.env
        ports:
            - 5432:5432
        volumes:
            - /var/lib/bak/postgres/data

    storage_manager:
        container_name: storage_manager
        build: 
            context: ./
            dockerfile: ./Dockerfile
        image: "ntw_storage/manager:latest"
        env_file:
            - ./conf/common.env
            - ./conf/manager.env
        environment: 
            DEBUG: 'false'
            #DEBUG: 'true'
        ports: 
            - 8000:8000
            - 5678:5678
        depends_on: 
            - storage_database
        command: bash /storage/entrypoint.sh manager
