# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeCloud(object):
    def setupUi(self, HomeCloud):
        HomeCloud.setObjectName("HomeCloud")
        HomeCloud.resize(349, 195)
        self.centralwidget = QtWidgets.QWidget(HomeCloud)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 52, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 40, 221, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 70, 221, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.LogIn = QtWidgets.QPushButton(self.centralwidget)
        self.LogIn.setGeometry(QtCore.QRect(140, 120, 75, 23))
        self.LogIn.setObjectName("LogIn")
        self.Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel.setGeometry(QtCore.QRect(240, 120, 75, 23))
        self.Cancel.setObjectName("Cancel")
        HomeCloud.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomeCloud)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 349, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        HomeCloud.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomeCloud)
        self.statusbar.setObjectName("statusbar")
        HomeCloud.setStatusBar(self.statusbar)
        self.actionVytvo_it_et = QtWidgets.QAction(HomeCloud)
        self.actionVytvo_it_et.setObjectName("actionVytvo_it_et")
        self.menuMenu.addAction(self.actionVytvo_it_et)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(HomeCloud)
        QtCore.QMetaObject.connectSlotsByName(HomeCloud)

    def retranslateUi(self, HomeCloud):
        _translate = QtCore.QCoreApplication.translate
        HomeCloud.setWindowTitle(_translate("HomeCloud", "Home cloud"))
        self.label.setText(_translate("HomeCloud", "User Name"))
        self.label_2.setText(_translate("HomeCloud", "Password"))
        self.LogIn.setText(_translate("HomeCloud", "LogIn"))
        self.Cancel.setText(_translate("HomeCloud", "Cancel"))
        self.menuMenu.setTitle(_translate("HomeCloud", "Menu"))
        self.actionVytvo_it_et.setText(_translate("HomeCloud", "Vytvořit účet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeCloud = QtWidgets.QMainWindow()
    ui = Ui_HomeCloud()
    ui.setupUi(HomeCloud)
    HomeCloud.show()
    sys.exit(app.exec_())
